# Writes a header naming the identity of this extension's conversion pipeline.
#
# The id is a hash of the EXTENSION'S SOURCE, not of the binary it becomes. That is the whole
# point: the same source built on macOS, Windows, Linux and Android has to produce the same id,
# because a client that downloads a host's converted .scn compares its own id against the one
# baked into that file. A binary hash or a compile timestamp would differ per platform and per
# rebuild, and every peer would reconvert — or worse, distrust — a map that was perfectly good.
#
# Run at BUILD time, not configure time. CONFIGURE_DEPENDS only re-runs a glob when the file
# LIST changes, so a configure-time hash goes stale the moment someone edits a file in place —
# which is exactly the case this exists to catch.
#
#   cmake -DGOLDSRC_ID_OUT=<header> -DGOLDSRC_ID_SOURCES=<;-list> -P pipeline_id.cmake

set(hashes "")
foreach(src IN LISTS GOLDSRC_ID_SOURCES)
    if(EXISTS "${src}")
        file(SHA256 "${src}" one)
        # The NAME, not the full path: a checkout in a different directory is the same pipeline.
        get_filename_component(name "${src}" NAME)
        string(APPEND hashes "${name}:${one}\n")
    endif()
endforeach()
string(SHA256 full "${hashes}")
string(SUBSTRING "${full}" 0 16 short)

file(WRITE "${GOLDSRC_ID_OUT}"
"// Generated by cmake/pipeline_id.cmake. Do not edit, do not commit.\n"
"#pragma once\n"
"#define GOLDSRC_PIPELINE_ID \"${short}\"\n")
